### PR TITLE
feat: adds ErrorOptions to Error constructor

### PR DESCRIPTION
**Pull request by NeerajGartia21**
## This PR

- adds `ErrorOptions` to `Error` constructor
- updates compiler option to `es2022`

### Related Issues

Fixes [this](https://github.com/open-feature/js-sdk-contrib/issues/713)

### CODE REVIEW

**Review by beeme1mr — COMMENTED** [review]
The change looks good to me but there are a few docs that should be updated prior to this PR being merged. Please change the compilation target to `es2022`.

- https://github.com/open-feature/js-sdk/blob/main/CONTRIBUTING.md
- https://github.com/open-feature/js-sdk/tree/main/packages/client

FYI @toddbaert, we specified `es2015` for the client SDK but we could update it to es2022 prior to a GA release.

**Comment by NeerajGartia21** [comment]
Thanks for the review. I've updated the compilation target to `es2022` and also updated the docs accordingly.

**Review by lukas-reining — DISMISSED** [review]
This looks good! I will have time to try to build it tomorrow.
Thanks for the PR! :)

**Review by beeme1mr — APPROVED** [review]

**Review by lukas-reining — APPROVED** [review]
Building works and the built SDK works in the playground, thanks!

**Comment by toddbaert** [comment]
Thanks for reviewing guys! I've been heads-down working on the .NET release.

Thanks to you for this contribution @NeerajGartia21 !

**Pull request merged**
